version: '3'
services:
  opensearch-hnsw-node1: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-hnsw-node1
    environment:
      - cluster.name=opensearch-hnsw-cluster # Name the cluster
      - node.name=opensearch-hnsw-node1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-hnsw-node1,opensearch-hnsw-node2 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-hnsw-node1,opensearch-hnsw-node2 # Nodes eligible to serve as cluster manager
      - "OPENSEARCH_JAVA_OPTS=-Xms6192m -Xmx6192m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}    # Sets the demo admin user password when using demo configuration, required for OpenSearch 2.12 and later
      - "DISABLE_SECURITY_PLUGIN=true" # Disables Security plugin
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-hnsw-data1:/usr/share/opensearch-hnsw/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-hnsw-net # All of the containers will join the same Docker bridge network
  opensearch-hnsw-node2:
    image: opensearchproject/opensearch:latest # This should be the same image used for opensearch-node1 to avoid issues
    container_name: opensearch-hnsw-node2
    environment:
      - cluster.name=opensearch-hnsw-cluster
      - node.name=opensearch-hnsw-node2
      - discovery.seed_hosts=opensearch-hnsw-node1,opensearch-hnsw-node2
      - cluster.initial_cluster_manager_nodes=opensearch-hnsw-node1,opensearch-hnsw-node2
      - "OPENSEARCH_JAVA_OPTS=-Xms6192m -Xmx6192m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - "DISABLE_SECURITY_PLUGIN=true" # Disables Security plugin
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-hnsw-data2:/usr/share/opensearch-hnsw/data
    networks:
      - opensearch-hnsw-net

volumes:
  opensearch-hnsw-data1:
  opensearch-hnsw-data2:

networks:
  opensearch-hnsw-net: