# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DocumentChunkMetadata

    DocumentChunkMetadata(;
        source=nothing,
        source_id=nothing,
        url=nothing,
        created_at=nothing,
        author=nothing,
        document_id=nothing,
    )

    - source::Source
    - source_id::String
    - url::String
    - created_at::String
    - author::String
    - document_id::String
"""
Base.@kwdef mutable struct DocumentChunkMetadata
    source = nothing # spec type: Union{ Nothing, Source }
    source_id::Union{Nothing, String} = nothing
    url::Union{Nothing, String} = nothing
    created_at::Union{Nothing, String} = nothing
    author::Union{Nothing, String} = nothing
    document_id::Union{Nothing, String} = nothing
end # type DocumentChunkMetadata

