# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DocumentChunk

    DocumentChunk(;
        id=nothing,
        text=nothing,
        metadata=nothing,
        embedding=nothing,
        score=nothing,
    )

    - id::String
    - text::String
    - metadata::DocumentChunkMetadata
    - embedding::Vector{Float64}
    - score::Float64
"""
Base.@kwdef mutable struct DocumentChunk
    id::Union{Nothing, String} = nothing
    text::Union{Nothing, String} = nothing
    metadata = nothing # spec type: Union{ Nothing, DocumentChunkMetadata }
    embedding::Union{Nothing, Vector{Float64}} = nothing
    score::Union{Nothing, Float64} = nothing
end # type DocumentChunk
